import { Footer, Header } from '@/components/layout';
import { WhatsAppFloating } from '@/components/shared/WhatsAppFloating';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Recreation center',
  description: 'Generated by create next app',
};

export default async function BaseLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header />
          <main>{children}</main>
          <WhatsAppFloating text="Здравствуйте" phone="+996701151539" />
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
