import { Footer, Header } from '@/components/layout';
import { WhatsAppFloating } from '@/components/shared/WhatsAppFloating';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, getTranslations } from 'next-intl/server';

import '@/app/globals.css';
import { Fancybox } from '@/components/ui';
import { getGeneralData } from '@/utils/fetch';
import 'swiper/css';
import 'swiper/css/effect-coverflow';
import 'swiper/css/pagination';

export const metadata: Metadata = {
  title: 'Recreation center',
  description: 'Generated by create next app',
};

export default async function BaseLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();
  const generalData = await getGeneralData();

  const t = await getTranslations('Actions');

  return (
    <html lang={locale}>
      <body>
        <AntdRegistry>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Header />
            <main>
              <Fancybox>{children}</Fancybox>
            </main>
            <WhatsAppFloating text={t('hello')} phone={generalData[0]?.phone[0]} />
            <Footer data={generalData} />
          </NextIntlClientProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
